### ISSUE TITLE
0.0.10版本的any-door启动时候报错NoClassDefined：com/fasterxml/jackson/datatype/jsr310/JavaTimeModule

### ISSUE THREAD

**Issue by meiMingle** [lgp547/any-door#16]
好像是我们项目里没有jackson-datatype-jsr310这个依赖，但是加上这个依赖之后又报错NoClassDefined：com/fasterxml/jackson/databind.ser/std/ToStringSerializerBase
。并且any-door插件似乎不允许使用0.0.10以下的any-door.jar，现在只能把0.0.9的jar改个文件名扔到0.0.10的本地仓库文件夹里凑合用

**Comment by lgp547** [comment]
any-door插件1.0.9版本，强制要求any-door版本0.0.10以上，因为一下修复需要配合起来使用，重新在中央仓库下载即可。
关于springboot和需要下载jar包，目前在开发中了，下个版本的插件，将直接把jar包一起，并且不再依赖springboot

**Comment by lgp547** [comment]
对于jackson的安排，也是会直接打包到jar包里面，不在需要使用方进行提供

**Comment by lgp547** [comment]
发布了新版本，使用看看是否还存在当前问题
