### ISSUE TITLE
Could not initialize class io.github.lgp547.anydoor.util.JsonUtil

### ISSUE THREAD

**Issue by clickear** [lgp547/any-door#21]
1. 安装插件
2. 启动服务，直接调用提示 Could not initialize class io.github.lgp547.anydoor.util.JsonUtil

**Comment by lgp547** [comment]
是最新版本1.3.1的插件吗？
1.3.1默认是采用attach，启动的时候不会也不用加载JsonUtil

**Comment by clickear** [comment]
> 

之前有安装过旧版的，卸载了有重装过1.3.1。使用的是agent方式
<img width="848" alt="image" src="https://github.com/lgp547/any-door/assets/12124172/cbed5c2e-158a-40d0-9757-c9ea080343e9">

**Comment by lgp547** [comment]
点击配置里面的移除jar包，重新启动看看
![image](https://github.com/lgp547/any-door/assets/51388510/0ba8d6bc-6845-4c25-bf82-671b248cc426)

**Comment by lgp547** [comment]
看异常，是没把第三方jar包加载进去，看看是否有依赖包
![image](https://github.com/lgp547/any-door/assets/51388510/6095d636-6840-4820-98d6-21fb51512a30)
![image](https://github.com/lgp547/any-door/assets/51388510/0926b6e7-17bc-4406-bd77-09ab2d73041e)

**Comment by clickear** [comment]
看了，这些都尝试了

> 看异常，是没把第三方jar包加载进去，看看是否有依赖包 ![image](https://user-images.githubusercontent.com/51388510/241835588-6095d636-6840-4820-98d6-21fb51512a30.png) ![image](https://user-images.githubusercontent.com/51388510/241835706-0926b6e7-17bc-4406-bd77-09ab2d73041e.png)
看起来，应该是JsonUtil初始化的时候失败了，导致加载不了类引起的。具体原因我排查看下
<img width="806" alt="image" src="https://github.com/lgp547/any-door/assets/12124172/3d1011d1-c562-4693-a784-1af42cda4115">

**Comment by lgp547** [comment]
是不是版本冲突了，你运行项目的jackson-core的版本是多少

**Comment by clickear** [comment]
> 是不是版本冲突了，你运行项目的jackson-core的版本是多少

看起来是版本冲突了。项目中使用2.9.7。

**Comment by clickear** [comment]
> 是不是版本冲突了，你运行项目的jackson-core的版本是多少

有没办法搞个bundle，这样就避免与原项目冲突了

**Comment by lgp547** [comment]
发了个新版本，临时兼容处理，再提审了，可以先直接用


---
目前是把依赖包打包进去了，但在执行的时候还得运行项目去加载相关类。
前面是考虑到版本冲突问题，使用者可自行替换版本，但目前看起来效果不得行，因为anyDoor core 里面的代码已经写死了，就算替换依赖版本，也无法往下走。

后续迭代：减少依赖第三方
[any-door-plugin.zip](https://github.com/lgp547/any-door/files/11620849/any-door-plugin.zip)

**Comment by lgp547** [comment]
新版本1.3.2已推送，更新后尝试看看

**Comment by clickear** [comment]
> 发了个新版本，临时兼容处理，再提审了，可以先直接用
> 
> 目前是把依赖包打包进去了，但在执行的时候还得运行项目去加载相关类。 前面是考虑到版本冲突问题，使用者可自行替换版本，但目前看起来效果不得行，因为anyDoor core 里面的代码已经写死了，就算替换依赖版本，也无法往下走。
> 
> 后续迭代：减少依赖第三方 [any-door-plugin.zip](https://github.com/lgp547/any-door/files/11620849/any-door-plugin.zip)

可以考虑，使用maven-shade-plugin插件。在打包的时候，把插件用到的类进行重命名。或者参考arthas进行类隔离

**Comment by lgp547** [comment]
> > 发布了一个新版本，临时兼顾处理，再提审了，可以先直接使用
> > 前面是把依赖包打包进去了，但是在执行的时候还得运行项目去加载相关类。前面是考虑到版本冲突问题，使用者可自行更换版本，但目前看起效果不得行，因为任何门芯里面的代码已经写死了，就算换依赖版本，也无法往下走。
> > 后续代：减少依赖第三方[any-door-plugin.zip](https://github.com/lgp547/any-door/files/11620849/any-door-plugin.zip)
> 
> 可以考虑，使用maven-shade-plugin插件。在打包的时候，把插件用到的类进入重名。或者参考arthas类进入类隔离

👍感谢提供思路
