### ISSUE TITLE
升级1.4.0版本后中文路径存在报错

### ISSUE THREAD

**Issue by wsj-hit** [lgp547/any-door#24]
![image](https://github.com/lgp547/any-door/assets/35788293/9e6057b8-6b78-4cbb-ba72-063229c120bb)
升级后出现

**Comment by lgp547** [comment]
临时解决：不填写参数或少量参数，然后卡断点后再set参数。
预计解决：下个版本

**Comment by lgp547** [comment]
升级到2.0.0版本再试试

**Comment by wsj-hit** [comment]
> 升级到2.0.0版本再试试

已解决 感谢大佬
