### ISSUE TITLE
建议参数编辑支持Json5格式

### ISSUE THREAD

**Issue by ZHLHZHU** [lgp547/any-door#39]
希望增加json5格式支持，以便于支持json注释，方便使用
<img width="694" alt="image" src="https://github.com/lgp547/any-door/assets/20608902/9dd4a135-25a3-4fff-8f7e-2d934c353442">

**Comment by lgp547** [comment]
右边有一个保存，可以多套存储常用的哦
后续迭代

**Comment by lgp547** [comment]
2.2.0版本已支持
