### ISSUE TITLE
期望可以设置上下文信息

### ISSUE THREAD

**Issue by SeSiTing** [lgp547/any-door#43]
代码中通常有XXXContext.getUserId()，正常来说这些信息是从网关解析放入上下文的。
但是any-door触发的调试没有上下文信息。
期望any-door在每次执行前可以固定的执行一段代码块，主动的设置一些必要的上下文信息

**Comment by wsj-hit** [comment]
支持 目前我的做法是在入口手动打断点 然后用Evaluate Expression调用一段代码

**Comment by lgp547** [comment]
2.2.0版本已支持
